trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    git clone https://github.com/apache/pulsar.git
    cd pulsar
    mvn install -DskipTests -Pcore-modules
    mvn test -pl pulsar-broker

  displayName: 'Run broker tests'
