trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    git clone --depth=1 https://github.com/apache/pulsar.git
    cd pulsar
    mvn -ntp -q install -DskipTests -Pcore-modules
    mvn test -pl pulsar-broker -Dgroups='broker'

  displayName: 'Run broker tests'
